title = "DSAC Boilerplate"  # From Git
gitRepoUrl = "https://github.com/SuitUpGames/roblox-dsac-boilerplate" # From Git

gitSourceBranch = "main"
changelog = true
classOrder = []

[docusaurus]
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "warn"

# From git:
organizationName = "SuitUpGames"
projectName = "DSAC Boilerplate"
url = "https://suitupgames.github.io"
baseUrl = "/roblox-dsac-boilerplate"
tagline = "Tagline"

[navbar]

[footer]
style = "dark"
copyright = "Copyright © 2023 Suit Up Games. Built with Moonwave and Docusaurus"

[[footer.links]]
title = "examples"

[[footer.links.items]]
label = "Suit Up Games"
href = "https://suitup.games/
"