[package]
name = "suitup/boilerplate"
description = "a boilerplate project for suit up games"
version = "0.0.1"
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"

[dependencies]
Knit = "sleitnick/knit@1.5.1"
Signal = "sleitnick/signal@1.5.0"
Comm = "sleitnick/comm@0.3.1"
TableUtil = "sleitnick/table-util@1.2.0"
Timer = "sleitnick/timer@1.1.2"
Promise = "evaera/promise@4.0.0"
Janitor = "howmanysmall/janitor@1.15.4"
WaitFor = "sleitnick/wait-for@0.2.1"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.3"